TOKENS = {
    'NUMBER': 'NUMBER',
    "IF": "IF",
    "ELSE": "ELSE",
    "EQ": "EQ",
    'IDENT': 'IDENTIFIER',
    'ASSIGN': '=',
    'PLUS': '+',
    'MINUS': '-',
    'MULT': '*',
    'DIV': '/',
    'COLON': 'COLON', 
    'LPAREN': '(',
    'RPAREN': ')',
    'IF': 'IF',
    'ELSE': 'ELSE',
    'WHILE': 'WHILE',
    'PRINT': 'PRINT',
    'EQ': '==',
    'NE': '!=',
    'LT': '<',
    'GT': '>',
    'LE': '<=',
    'GE': '>=',
    'EOF': 'EOF'
}
